In [18]:
# here we first import the mglearb for futher operations

In [1]:
import mglearn

In [19]:
# now import the datasets in two dimensions i.e. X and Y

In [2]:
x , y =mglearn.datasets.load_extended_boston()

C:\Users\AYUSH\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (

In [3]:
from sklearn.model_selection import train_test_split

In [4]:
x_train, x_test, y_train, y_test = train_test_split(x,y,random_state = 0)

In [5]:
x_train

array([[0.00207947, 0.22      , 0.19794721, ..., 0.96119883, 0.45259981,
        0.21311573],
       [0.00108981, 0.25      , 0.17118768, ..., 1.        , 0.2066777 ,
        0.04271567],
       [0.00110566, 0.4       , 0.2181085 , ..., 0.96179224, 0.11690584,
        0.0142099 ],
       ...,
       [0.00162594, 0.        , 0.35007331, ..., 0.98798327, 0.23505388,
        0.05592233],
       [0.0025059 , 0.        , 0.23643695, ..., 0.97913066, 0.46608557,
        0.22186595],
       [0.00149286, 0.        , 0.13159824, ..., 1.        , 0.35761589,
        0.12788913]])

In [6]:
x_test

array([[6.84726112e-04, 0.00000000e+00, 1.01906158e-01, ...,
        8.93606039e-01, 1.46334834e-01, 2.39634501e-02],
       [1.03697791e-01, 0.00000000e+00, 6.46627566e-01, ...,
        8.50936235e-01, 1.98543157e-01, 4.63247226e-02],
       [1.21310718e-03, 0.00000000e+00, 4.92302053e-01, ...,
        9.84127236e-01, 2.40069523e-01, 5.85629316e-02],
       ...,
       [3.85613648e-03, 0.00000000e+00, 3.46041056e-01, ...,
        9.96674311e-01, 2.26994668e-01, 5.16985122e-02],
       [1.03596858e-03, 0.00000000e+00, 9.23387097e-01, ...,
        9.13596232e-01, 4.18040374e-01, 1.91285546e-01],
       [7.72283834e-04, 3.30000000e-01, 6.30498534e-02, ...,
        1.00000000e+00, 1.30794702e-01, 1.71072541e-02]])

In [7]:
y_train

array([18.5, 19.6, 33.2, 13.1,  7.5, 13.6, 17.4,  8.4, 35.4, 24. , 13.4,
       26.2,  7.2, 13.1, 24.5, 37.2, 25. , 24.1, 16.6, 32.9, 36.2, 11. ,
        7.2, 22.8, 28.7, 14.4, 24.4, 18.1, 22.5, 20.5, 15.2, 17.4, 13.6,
        8.7, 18.2, 35.4, 31.7, 33. , 22.2, 20.4, 23.9, 25. , 12.7, 29.1,
       12. , 17.7, 27. , 20.6, 10.2, 17.5, 19.7, 29.8, 20.5, 14.9, 10.9,
       19.5, 22.7, 19.5, 24.6, 25. , 24.5, 50. , 14.3, 11.8, 31. , 28.7,
       16.2, 43.5, 25. , 22. , 19.9, 22.1, 46. , 22.9, 20.2, 43.1, 34.6,
       13.8, 24.3, 21.5, 24.4, 21.2, 23.8, 26.6, 25.1,  9.6, 19.4, 19.4,
        9.5, 14. , 26.5, 13.8, 34.7, 16.3, 21.7, 17.5, 15.6, 20.9, 21.7,
       12.7, 18.5, 23.7, 19.3, 12.7, 21.6, 23.2, 29.6, 21.2, 23.8, 17.1,
       22. , 36.5, 18.8, 21.9, 23.1, 20.2, 17.4, 37. , 24.1, 36.2, 15.7,
       32.2, 13.5, 17.9, 13.3, 11.7, 41.7, 18.4, 13.1, 25. , 21.2, 16. ,
       34.9, 25.2, 24.8, 21.5, 23.4, 18.9, 10.8, 21. , 27.5, 17.5, 13.5,
       28.7, 14.8, 19.1, 28.6, 13.1, 19. , 11.3, 13

In [8]:
y_test

array([22.6, 50. , 23. ,  8.3, 21.2, 19.9, 20.6, 18.7, 16.1, 18.6,  8.8,
       17.2, 14.9, 10.5, 50. , 29. , 23. , 33.3, 29.4, 21. , 23.8, 19.1,
       20.4, 29.1, 19.3, 23.1, 19.6, 19.4, 38.7, 18.7, 14.6, 20. , 20.5,
       20.1, 23.6, 16.8,  5.6, 50. , 14.5, 13.3, 23.9, 20. , 19.8, 13.8,
       16.5, 21.6, 20.3, 17. , 11.8, 27.5, 15.6, 23.1, 24.3, 42.8, 15.6,
       21.7, 17.1, 17.2, 15. , 21.7, 18.6, 21. , 33.1, 31.5, 20.1, 29.8,
       15.2, 15. , 27.5, 22.6, 20. , 21.4, 23.5, 31.2, 23.7,  7.4, 48.3,
       24.4, 22.6, 18.3, 23.3, 17.1, 27.9, 44.8, 50. , 23. , 21.4, 10.2,
       23.3, 23.2, 18.9, 13.4, 21.9, 24.8, 11.9, 24.3, 13.8, 24.7, 14.1,
       18.7, 28.1, 19.8, 26.7, 21.7, 22. , 22.9, 10.4, 21.9, 20.6, 26.4,
       41.3, 17.2, 27.1, 20.4, 16.5, 24.4,  8.4, 23. ,  9.7, 50. , 30.5,
       12.3, 19.4, 21.2, 20.3, 18.8, 33.4])

In [20]:
# here we import the Linear Regression model from Linear Model

In [9]:
from sklearn.linear_model import LinearRegression

In [21]:
# giving the alias as lr for Linear Regression

In [10]:
lr = LinearRegression()

In [13]:
lr

LinearRegression()

In [22]:
# now we are fitting the linear regression model with the training data

In [15]:
lr.fit(x_train,y_train)

LinearRegression()

In [23]:
# here we are analyzing the training set score

In [24]:
print("Training set score : {:.2f}".format(lr.score(x_train,y_train)))

Training set score : 0.95


In [25]:
# and finally analyzing the testing set score

In [17]:
print("Testing set score : {:.2f}".format(lr.score(x_test,y_test)))

Testing set score : 0.61
